logging:

  level: INFO

  loggers:
    io.dropwizard: INFO

    # Logs WebServices REST requests and responses when INFO
    com.sun.jersey.api.container.filter.LoggingFilter: INFO

    # Logs MICROS OWS SOAP requests and responses when DEBUG
    org.apache.cxf: INFO
    org.apache.cxf.services: INFO
    org.apache.cxf.interceptor: INFO

  appenders:
    - type: file
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/main.log

      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/main-%d.log.gz

      # The number of archived files to keep.
      archivedFileCount: 5

      # The timezone used to format dates.
      timeZone: UTC

    - type: console

server:
  applicationConnectors:
  - type: http
    port: 8080

  adminConnectors:
  - type: http
    port: 8081

  requestLog:
    # The timezone used to format dates.
    timeZone: UTC

    appenders:
          - type: file
            # The file to which current statements will be logged.
            currentLogFilename: ./logs/requests.log

            # When the log file rotates, the archived log will be renamed to this and gzipped. The
            # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
            # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
            archivedLogFilenamePattern: ./logs/requests-%d.log.gz

            # The number of archived files to keep.
            archivedFileCount: 5

          - type: console
