//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 06:49:58 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvailableRoomRate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailableRoomRate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RatePlan" type="{http://webservices.micros.com/og/4.3/HotelCommon/}RatePlan" minOccurs="0"/>
 *         &lt;element name="RoomType" type="{http://webservices.micros.com/og/4.3/HotelCommon/}RoomType" minOccurs="0"/>
 *         &lt;element name="FirstDayAmount" type="{http://webservices.micros.com/og/4.3/Common/}Amount" minOccurs="0"/>
 *         &lt;element name="TotalStayAmount" type="{http://webservices.micros.com/og/4.3/Common/}Amount" minOccurs="0"/>
 *         &lt;element name="AdultRate" type="{http://webservices.micros.com/og/4.3/Common/}Amount" minOccurs="0"/>
 *         &lt;element name="ChildRate" type="{http://webservices.micros.com/og/4.3/Common/}Amount" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailableRoomRate", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/", propOrder = {
    "ratePlan",
    "roomType",
    "firstDayAmount",
    "totalStayAmount",
    "adultRate",
    "childRate"
})
public class AvailableRoomRate {

    @XmlElement(name = "RatePlan", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected RatePlan ratePlan;
    @XmlElement(name = "RoomType", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected RoomType roomType;
    @XmlElement(name = "FirstDayAmount", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Amount firstDayAmount;
    @XmlElement(name = "TotalStayAmount", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Amount totalStayAmount;
    @XmlElement(name = "AdultRate", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Amount adultRate;
    @XmlElement(name = "ChildRate", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Amount childRate;
    @XmlAttribute(name = "Status")
    protected String status;

    /**
     * Gets the value of the ratePlan property.
     * 
     * @return
     *     possible object is
     *     {@link RatePlan }
     *     
     */
    public RatePlan getRatePlan() {
        return ratePlan;
    }

    /**
     * Sets the value of the ratePlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatePlan }
     *     
     */
    public void setRatePlan(RatePlan value) {
        this.ratePlan = value;
    }

    /**
     * Gets the value of the roomType property.
     * 
     * @return
     *     possible object is
     *     {@link RoomType }
     *     
     */
    public RoomType getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomType }
     *     
     */
    public void setRoomType(RoomType value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the firstDayAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getFirstDayAmount() {
        return firstDayAmount;
    }

    /**
     * Sets the value of the firstDayAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setFirstDayAmount(Amount value) {
        this.firstDayAmount = value;
    }

    /**
     * Gets the value of the totalStayAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getTotalStayAmount() {
        return totalStayAmount;
    }

    /**
     * Sets the value of the totalStayAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setTotalStayAmount(Amount value) {
        this.totalStayAmount = value;
    }

    /**
     * Gets the value of the adultRate property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getAdultRate() {
        return adultRate;
    }

    /**
     * Sets the value of the adultRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setAdultRate(Amount value) {
        this.adultRate = value;
    }

    /**
     * Gets the value of the childRate property.
     * 
     * @return
     *     possible object is
     *     {@link Amount }
     *     
     */
    public Amount getChildRate() {
        return childRate;
    }

    /**
     * Sets the value of the childRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amount }
     *     
     */
    public void setChildRate(Amount value) {
        this.childRate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
