//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 06:33:28 PM IST 
//


package com.micros.pms.bean;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FacilityInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacilityInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GuestRooms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GuestRoom" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RoomDescription" type="{http://webservices.micros.com/og/4.3/Common/}DescriptiveText" minOccurs="0"/>
 *                             &lt;element name="AmenityInfo" type="{http://webservices.micros.com/og/4.3/HotelCommon/}AmenityInfo" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="maxOccupancy" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="totalRooms" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Restaurants" type="{http://webservices.micros.com/og/4.3/HotelCommon/}RestaurantsType" minOccurs="0"/>
 *         &lt;element name="MeetingRooms" type="{http://webservices.micros.com/og/4.3/HotelCommon/}MeetingRoomsType" minOccurs="0"/>
 *         &lt;element name="Attractions" type="{http://webservices.micros.com/og/4.3/HotelCommon/}AttractionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dateOpened" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="dateRennovated" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacilityInfoType", propOrder = {
    "guestRooms",
    "restaurants",
    "meetingRooms",
    "attractions"
})
public class FacilityInfoType {

    @XmlElement(name = "GuestRooms")
    protected FacilityInfoType.GuestRooms guestRooms;
    @XmlElement(name = "Restaurants")
    protected RestaurantsType restaurants;
    @XmlElement(name = "MeetingRooms")
    protected MeetingRoomsType meetingRooms;
    @XmlElement(name = "Attractions")
    protected AttractionsType attractions;
    @XmlAttribute
    protected XMLGregorianCalendar dateOpened;
    @XmlAttribute
    protected XMLGregorianCalendar dateRennovated;

    /**
     * Gets the value of the guestRooms property.
     * 
     * @return
     *     possible object is
     *     {@link FacilityInfoType.GuestRooms }
     *     
     */
    public FacilityInfoType.GuestRooms getGuestRooms() {
        return guestRooms;
    }

    /**
     * Sets the value of the guestRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacilityInfoType.GuestRooms }
     *     
     */
    public void setGuestRooms(FacilityInfoType.GuestRooms value) {
        this.guestRooms = value;
    }

    /**
     * Gets the value of the restaurants property.
     * 
     * @return
     *     possible object is
     *     {@link RestaurantsType }
     *     
     */
    public RestaurantsType getRestaurants() {
        return restaurants;
    }

    /**
     * Sets the value of the restaurants property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestaurantsType }
     *     
     */
    public void setRestaurants(RestaurantsType value) {
        this.restaurants = value;
    }

    /**
     * Gets the value of the meetingRooms property.
     * 
     * @return
     *     possible object is
     *     {@link MeetingRoomsType }
     *     
     */
    public MeetingRoomsType getMeetingRooms() {
        return meetingRooms;
    }

    /**
     * Sets the value of the meetingRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeetingRoomsType }
     *     
     */
    public void setMeetingRooms(MeetingRoomsType value) {
        this.meetingRooms = value;
    }

    /**
     * Gets the value of the attractions property.
     * 
     * @return
     *     possible object is
     *     {@link AttractionsType }
     *     
     */
    public AttractionsType getAttractions() {
        return attractions;
    }

    /**
     * Sets the value of the attractions property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttractionsType }
     *     
     */
    public void setAttractions(AttractionsType value) {
        this.attractions = value;
    }

    /**
     * Gets the value of the dateOpened property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOpened() {
        return dateOpened;
    }

    /**
     * Sets the value of the dateOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOpened(XMLGregorianCalendar value) {
        this.dateOpened = value;
    }

    /**
     * Gets the value of the dateRennovated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateRennovated() {
        return dateRennovated;
    }

    /**
     * Sets the value of the dateRennovated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateRennovated(XMLGregorianCalendar value) {
        this.dateRennovated = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GuestRoom" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RoomDescription" type="{http://webservices.micros.com/og/4.3/Common/}DescriptiveText" minOccurs="0"/>
     *                   &lt;element name="AmenityInfo" type="{http://webservices.micros.com/og/4.3/HotelCommon/}AmenityInfo" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="maxOccupancy" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="totalRooms" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "guestRoom"
    })
    public static class GuestRooms {

        @XmlElement(name = "GuestRoom", required = true)
        protected List<FacilityInfoType.GuestRooms.GuestRoom> guestRoom;
        @XmlAttribute
        protected String totalRooms;

        /**
         * Gets the value of the guestRoom property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the guestRoom property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGuestRoom().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FacilityInfoType.GuestRooms.GuestRoom }
         * 
         * 
         */
        public List<FacilityInfoType.GuestRooms.GuestRoom> getGuestRoom() {
            if (guestRoom == null) {
                guestRoom = new ArrayList<FacilityInfoType.GuestRooms.GuestRoom>();
            }
            return this.guestRoom;
        }

        /**
         * Gets the value of the totalRooms property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalRooms() {
            return totalRooms;
        }

        /**
         * Sets the value of the totalRooms property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalRooms(String value) {
            this.totalRooms = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RoomDescription" type="{http://webservices.micros.com/og/4.3/Common/}DescriptiveText" minOccurs="0"/>
         *         &lt;element name="AmenityInfo" type="{http://webservices.micros.com/og/4.3/HotelCommon/}AmenityInfo" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="maxOccupancy" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "roomDescription",
            "amenityInfo"
        })
        public static class GuestRoom {

            @XmlElement(name = "RoomDescription")
            protected DescriptiveText roomDescription;
            @XmlElement(name = "AmenityInfo")
            protected AmenityInfo amenityInfo;
            @XmlAttribute
            protected String code;
            @XmlAttribute
            protected BigInteger maxOccupancy;

            /**
             * Gets the value of the roomDescription property.
             * 
             * @return
             *     possible object is
             *     {@link DescriptiveText }
             *     
             */
            public DescriptiveText getRoomDescription() {
                return roomDescription;
            }

            /**
             * Sets the value of the roomDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link DescriptiveText }
             *     
             */
            public void setRoomDescription(DescriptiveText value) {
                this.roomDescription = value;
            }

            /**
             * Gets the value of the amenityInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AmenityInfo }
             *     
             */
            public AmenityInfo getAmenityInfo() {
                return amenityInfo;
            }

            /**
             * Sets the value of the amenityInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AmenityInfo }
             *     
             */
            public void setAmenityInfo(AmenityInfo value) {
                this.amenityInfo = value;
            }

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the maxOccupancy property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMaxOccupancy() {
                return maxOccupancy;
            }

            /**
             * Sets the value of the maxOccupancy property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMaxOccupancy(BigInteger value) {
                this.maxOccupancy = value;
            }

        }

    }

}
