//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 06:33:28 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GdsTotalPriceList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GdsTotalPriceList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RateCalculation" type="{http://webservices.micros.com/og/4.3/HotelCommon/}RateCalculation" minOccurs="0"/>
 *         &lt;element name="AdditionalBedAmounts" type="{http://webservices.micros.com/og/4.3/HotelCommon/}AdditionalBedAmountList" minOccurs="0"/>
 *         &lt;element name="RoomQuality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BedType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GdsTotalPriceList", namespace = "http://webservices.micros.com/og/4.3/Availability/", propOrder = {
    "rateCalculation",
    "additionalBedAmounts",
    "roomQuality",
    "bedType"
})
public class GdsTotalPriceList {

    @XmlElement(name = "RateCalculation", namespace = "http://webservices.micros.com/og/4.3/Availability/")
    protected RateCalculation rateCalculation;
    @XmlElement(name = "AdditionalBedAmounts", namespace = "http://webservices.micros.com/og/4.3/Availability/")
    protected AdditionalBedAmountList additionalBedAmounts;
    @XmlElement(name = "RoomQuality", namespace = "http://webservices.micros.com/og/4.3/Availability/")
    protected String roomQuality;
    @XmlElement(name = "BedType", namespace = "http://webservices.micros.com/og/4.3/Availability/")
    protected String bedType;

    /**
     * Gets the value of the rateCalculation property.
     * 
     * @return
     *     possible object is
     *     {@link RateCalculation }
     *     
     */
    public RateCalculation getRateCalculation() {
        return rateCalculation;
    }

    /**
     * Sets the value of the rateCalculation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateCalculation }
     *     
     */
    public void setRateCalculation(RateCalculation value) {
        this.rateCalculation = value;
    }

    /**
     * Gets the value of the additionalBedAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalBedAmountList }
     *     
     */
    public AdditionalBedAmountList getAdditionalBedAmounts() {
        return additionalBedAmounts;
    }

    /**
     * Sets the value of the additionalBedAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalBedAmountList }
     *     
     */
    public void setAdditionalBedAmounts(AdditionalBedAmountList value) {
        this.additionalBedAmounts = value;
    }

    /**
     * Gets the value of the roomQuality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomQuality() {
        return roomQuality;
    }

    /**
     * Sets the value of the roomQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomQuality(String value) {
        this.roomQuality = value;
    }

    /**
     * Gets the value of the bedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBedType() {
        return bedType;
    }

    /**
     * Sets the value of the bedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBedType(String value) {
        this.bedType = value;
    }

}
