//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 06:33:28 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AwardPointsInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AwardPointsInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalPoints" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="BasePoints" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="BonusPoints" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MiscPoints" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TotalPointsRange" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="BasePointsRange" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="BonusPointsRange" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MiscPointsRange" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AwardPointsInfo", namespace = "http://webservices.micros.com/og/4.3/Membership/", propOrder = {
    "totalPoints",
    "basePoints",
    "bonusPoints",
    "miscPoints",
    "totalPointsRange",
    "basePointsRange",
    "bonusPointsRange",
    "miscPointsRange"
})
public class AwardPointsInfo {

    @XmlElement(name = "TotalPoints", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double totalPoints;
    @XmlElement(name = "BasePoints", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double basePoints;
    @XmlElement(name = "BonusPoints", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double bonusPoints;
    @XmlElement(name = "MiscPoints", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double miscPoints;
    @XmlElement(name = "TotalPointsRange", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double totalPointsRange;
    @XmlElement(name = "BasePointsRange", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double basePointsRange;
    @XmlElement(name = "BonusPointsRange", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double bonusPointsRange;
    @XmlElement(name = "MiscPointsRange", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected Double miscPointsRange;

    /**
     * Gets the value of the totalPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalPoints() {
        return totalPoints;
    }

    /**
     * Sets the value of the totalPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalPoints(Double value) {
        this.totalPoints = value;
    }

    /**
     * Gets the value of the basePoints property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBasePoints() {
        return basePoints;
    }

    /**
     * Sets the value of the basePoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBasePoints(Double value) {
        this.basePoints = value;
    }

    /**
     * Gets the value of the bonusPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBonusPoints() {
        return bonusPoints;
    }

    /**
     * Sets the value of the bonusPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBonusPoints(Double value) {
        this.bonusPoints = value;
    }

    /**
     * Gets the value of the miscPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMiscPoints() {
        return miscPoints;
    }

    /**
     * Sets the value of the miscPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMiscPoints(Double value) {
        this.miscPoints = value;
    }

    /**
     * Gets the value of the totalPointsRange property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTotalPointsRange() {
        return totalPointsRange;
    }

    /**
     * Sets the value of the totalPointsRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTotalPointsRange(Double value) {
        this.totalPointsRange = value;
    }

    /**
     * Gets the value of the basePointsRange property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBasePointsRange() {
        return basePointsRange;
    }

    /**
     * Sets the value of the basePointsRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBasePointsRange(Double value) {
        this.basePointsRange = value;
    }

    /**
     * Gets the value of the bonusPointsRange property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBonusPointsRange() {
        return bonusPointsRange;
    }

    /**
     * Sets the value of the bonusPointsRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBonusPointsRange(Double value) {
        this.bonusPointsRange = value;
    }

    /**
     * Gets the value of the miscPointsRange property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMiscPointsRange() {
        return miscPointsRange;
    }

    /**
     * Sets the value of the miscPointsRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMiscPointsRange(Double value) {
        this.miscPointsRange = value;
    }

}
