//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 06:33:28 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncryptedSwipe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptedSwipe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrackIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SwiperType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SwiperID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaskedPAN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Track1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Track2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KeySerialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptedSwipe", namespace = "http://webservices.micros.com/og/4.3/Common/", propOrder = {
    "trackIndicator",
    "swiperType",
    "swiperID",
    "maskedPAN",
    "track1",
    "track2",
    "keySerialNumber"
})
public class EncryptedSwipe {

    @XmlElement(name = "TrackIndicator", namespace = "http://webservices.micros.com/og/4.3/Common/", required = true)
    protected String trackIndicator;
    @XmlElement(name = "SwiperType", namespace = "http://webservices.micros.com/og/4.3/Common/", required = true)
    protected String swiperType;
    @XmlElement(name = "SwiperID", namespace = "http://webservices.micros.com/og/4.3/Common/")
    protected String swiperID;
    @XmlElement(name = "MaskedPAN", namespace = "http://webservices.micros.com/og/4.3/Common/", required = true)
    protected String maskedPAN;
    @XmlElement(name = "Track1", namespace = "http://webservices.micros.com/og/4.3/Common/")
    protected String track1;
    @XmlElement(name = "Track2", namespace = "http://webservices.micros.com/og/4.3/Common/")
    protected String track2;
    @XmlElement(name = "KeySerialNumber", namespace = "http://webservices.micros.com/og/4.3/Common/", required = true)
    protected String keySerialNumber;

    /**
     * Gets the value of the trackIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackIndicator() {
        return trackIndicator;
    }

    /**
     * Sets the value of the trackIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackIndicator(String value) {
        this.trackIndicator = value;
    }

    /**
     * Gets the value of the swiperType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwiperType() {
        return swiperType;
    }

    /**
     * Sets the value of the swiperType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwiperType(String value) {
        this.swiperType = value;
    }

    /**
     * Gets the value of the swiperID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwiperID() {
        return swiperID;
    }

    /**
     * Sets the value of the swiperID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwiperID(String value) {
        this.swiperID = value;
    }

    /**
     * Gets the value of the maskedPAN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaskedPAN() {
        return maskedPAN;
    }

    /**
     * Sets the value of the maskedPAN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaskedPAN(String value) {
        this.maskedPAN = value;
    }

    /**
     * Gets the value of the track1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrack1() {
        return track1;
    }

    /**
     * Sets the value of the track1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrack1(String value) {
        this.track1 = value;
    }

    /**
     * Gets the value of the track2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrack2() {
        return track2;
    }

    /**
     * Sets the value of the track2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrack2(String value) {
        this.track2 = value;
    }

    /**
     * Gets the value of the keySerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeySerialNumber() {
        return keySerialNumber;
    }

    /**
     * Sets the value of the keySerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeySerialNumber(String value) {
        this.keySerialNumber = value;
    }

}
