//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 06:33:28 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Name Lookup General Criteria is only used for O2G service
 * 
 * <p>Java class for NameLookupAll complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameLookupAll">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MembershipType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MembershipNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActiveYn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="LookupVaultedCardData" type="{http://webservices.micros.com/og/4.3/Name/}LookupVaultedCardType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="NativeName" type="{http://webservices.micros.com/og/4.3/Name/}NativeName" minOccurs="0"/>
 *         &lt;element name="NoOfRows" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameLookupAll", namespace = "http://webservices.micros.com/og/4.3/Name/", propOrder = {
    "lastName",
    "firstName",
    "membershipType",
    "membershipNumber",
    "cardCode",
    "emailAddress",
    "activeYn",
    "cardNumber",
    "lookupVaultedCardData",
    "nativeName",
    "noOfRows"
})
public class NameLookupAll {

    @XmlElement(name = "LastName", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String lastName;
    @XmlElement(name = "FirstName", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String firstName;
    @XmlElement(name = "MembershipType", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String membershipType;
    @XmlElement(name = "MembershipNumber", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String membershipNumber;
    @XmlElement(name = "CardCode", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String cardCode;
    @XmlElement(name = "EmailAddress", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String emailAddress;
    @XmlElement(name = "ActiveYn", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String activeYn;
    @XmlElement(name = "CardNumber", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected String cardNumber;
    @XmlElement(name = "LookupVaultedCardData", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected LookupVaultedCardType lookupVaultedCardData;
    @XmlElement(name = "NativeName", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected NativeName nativeName;
    @XmlElement(name = "NoOfRows", namespace = "http://webservices.micros.com/og/4.3/Name/")
    protected Double noOfRows;

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the membershipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembershipType() {
        return membershipType;
    }

    /**
     * Sets the value of the membershipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembershipType(String value) {
        this.membershipType = value;
    }

    /**
     * Gets the value of the membershipNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembershipNumber() {
        return membershipNumber;
    }

    /**
     * Sets the value of the membershipNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembershipNumber(String value) {
        this.membershipNumber = value;
    }

    /**
     * Gets the value of the cardCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCode() {
        return cardCode;
    }

    /**
     * Sets the value of the cardCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCode(String value) {
        this.cardCode = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the activeYn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveYn() {
        return activeYn;
    }

    /**
     * Sets the value of the activeYn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveYn(String value) {
        this.activeYn = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the lookupVaultedCardData property.
     * 
     * @return
     *     possible object is
     *     {@link LookupVaultedCardType }
     *     
     */
    public LookupVaultedCardType getLookupVaultedCardData() {
        return lookupVaultedCardData;
    }

    /**
     * Sets the value of the lookupVaultedCardData property.
     * 
     * @param value
     *     allowed object is
     *     {@link LookupVaultedCardType }
     *     
     */
    public void setLookupVaultedCardData(LookupVaultedCardType value) {
        this.lookupVaultedCardData = value;
    }

    /**
     * Gets the value of the nativeName property.
     * 
     * @return
     *     possible object is
     *     {@link NativeName }
     *     
     */
    public NativeName getNativeName() {
        return nativeName;
    }

    /**
     * Sets the value of the nativeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NativeName }
     *     
     */
    public void setNativeName(NativeName value) {
        this.nativeName = value;
    }

    /**
     * Gets the value of the noOfRows property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNoOfRows() {
        return noOfRows;
    }

    /**
     * Sets the value of the noOfRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNoOfRows(Double value) {
        this.noOfRows = value;
    }

}
