//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 06:49:58 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PayRouting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayRouting">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoutingType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoutingInstructionsId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Resort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResvNameID" type="{http://webservices.micros.com/og/4.3/Common/}UniqueID" minOccurs="0"/>
 *         &lt;element name="RoutingCodes" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}RoutingInstructionCodes" minOccurs="0"/>
 *         &lt;element name="BillToNameID" type="{http://webservices.micros.com/og/4.3/Common/}UniqueID" minOccurs="0"/>
 *         &lt;element name="BeginDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ToResvNameID" type="{http://webservices.micros.com/og/4.3/Common/}UniqueID" minOccurs="0"/>
 *         &lt;element name="BillingInstructionCode" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="AddTransaction" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="AddressID" type="{http://webservices.micros.com/og/4.3/Common/}UniqueID" minOccurs="0"/>
 *         &lt;element name="AuthorizerID" type="{http://webservices.micros.com/og/4.3/Common/}UniqueID" minOccurs="0"/>
 *         &lt;element name="RequestedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccountCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CreditLimit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="LimitUsed" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Declined" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DeclinedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompVoucherNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompCovers" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="CompTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoutingPercent" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RoutingLimitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MembershipID" type="{http://webservices.micros.com/og/4.3/Common/}UniqueID" minOccurs="0"/>
 *         &lt;element name="Day1" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Day2" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Day3" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Day4" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Day5" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Day6" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Day7" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DayString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Daily" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Owner" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Room" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RoutingInstruction" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Window" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayRouting", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/", propOrder = {
    "routingType",
    "routingInstructionsId",
    "resort",
    "resvNameID",
    "routingCodes",
    "billToNameID",
    "beginDate",
    "toResvNameID",
    "billingInstructionCode",
    "endDate",
    "addTransaction",
    "addressID",
    "authorizerID",
    "requestedBy",
    "accountCode",
    "creditLimit",
    "limitUsed",
    "comments",
    "declined",
    "declinedBy",
    "compVoucherNo",
    "compCovers",
    "compTypeCode",
    "routingPercent",
    "routingLimitType",
    "membershipID",
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7",
    "dayString",
    "daily"
})
public class PayRouting {

    @XmlElement(name = "RoutingType", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String routingType;
    @XmlElement(name = "RoutingInstructionsId", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String routingInstructionsId;
    @XmlElement(name = "Resort", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String resort;
    @XmlElement(name = "ResvNameID", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected UniqueID resvNameID;
    @XmlElement(name = "RoutingCodes", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected RoutingInstructionCodes routingCodes;
    @XmlElement(name = "BillToNameID", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected UniqueID billToNameID;
    @XmlElement(name = "BeginDate", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected XMLGregorianCalendar beginDate;
    @XmlElement(name = "ToResvNameID", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected UniqueID toResvNameID;
    @XmlElement(name = "BillingInstructionCode", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Double billingInstructionCode;
    @XmlElement(name = "EndDate", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "AddTransaction", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean addTransaction;
    @XmlElement(name = "AddressID", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected UniqueID addressID;
    @XmlElement(name = "AuthorizerID", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected UniqueID authorizerID;
    @XmlElement(name = "RequestedBy", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String requestedBy;
    @XmlElement(name = "AccountCode", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String accountCode;
    @XmlElement(name = "CreditLimit", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Double creditLimit;
    @XmlElement(name = "LimitUsed", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Double limitUsed;
    @XmlElement(name = "Comments", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String comments;
    @XmlElement(name = "Declined", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean declined;
    @XmlElement(name = "DeclinedBy", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String declinedBy;
    @XmlElement(name = "CompVoucherNo", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String compVoucherNo;
    @XmlElement(name = "CompCovers", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Double compCovers;
    @XmlElement(name = "CompTypeCode", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String compTypeCode;
    @XmlElement(name = "RoutingPercent", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Integer routingPercent;
    @XmlElement(name = "RoutingLimitType", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String routingLimitType;
    @XmlElement(name = "MembershipID", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected UniqueID membershipID;
    @XmlElement(name = "Day1", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean day1;
    @XmlElement(name = "Day2", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean day2;
    @XmlElement(name = "Day3", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean day3;
    @XmlElement(name = "Day4", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean day4;
    @XmlElement(name = "Day5", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean day5;
    @XmlElement(name = "Day6", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean day6;
    @XmlElement(name = "Day7", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean day7;
    @XmlElement(name = "DayString", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String dayString;
    @XmlElement(name = "Daily", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Boolean daily;
    @XmlAttribute(name = "Owner", required = true)
    protected String owner;
    @XmlAttribute(name = "Room")
    protected String room;
    @XmlAttribute(name = "RoutingInstruction", required = true)
    protected String routingInstruction;
    @XmlAttribute(name = "Window", required = true)
    protected int window;

    /**
     * Gets the value of the routingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingType() {
        return routingType;
    }

    /**
     * Sets the value of the routingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingType(String value) {
        this.routingType = value;
    }

    /**
     * Gets the value of the routingInstructionsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingInstructionsId() {
        return routingInstructionsId;
    }

    /**
     * Sets the value of the routingInstructionsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingInstructionsId(String value) {
        this.routingInstructionsId = value;
    }

    /**
     * Gets the value of the resort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResort() {
        return resort;
    }

    /**
     * Sets the value of the resort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResort(String value) {
        this.resort = value;
    }

    /**
     * Gets the value of the resvNameID property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getResvNameID() {
        return resvNameID;
    }

    /**
     * Sets the value of the resvNameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setResvNameID(UniqueID value) {
        this.resvNameID = value;
    }

    /**
     * Gets the value of the routingCodes property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingInstructionCodes }
     *     
     */
    public RoutingInstructionCodes getRoutingCodes() {
        return routingCodes;
    }

    /**
     * Sets the value of the routingCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingInstructionCodes }
     *     
     */
    public void setRoutingCodes(RoutingInstructionCodes value) {
        this.routingCodes = value;
    }

    /**
     * Gets the value of the billToNameID property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getBillToNameID() {
        return billToNameID;
    }

    /**
     * Sets the value of the billToNameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setBillToNameID(UniqueID value) {
        this.billToNameID = value;
    }

    /**
     * Gets the value of the beginDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBeginDate() {
        return beginDate;
    }

    /**
     * Sets the value of the beginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBeginDate(XMLGregorianCalendar value) {
        this.beginDate = value;
    }

    /**
     * Gets the value of the toResvNameID property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getToResvNameID() {
        return toResvNameID;
    }

    /**
     * Sets the value of the toResvNameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setToResvNameID(UniqueID value) {
        this.toResvNameID = value;
    }

    /**
     * Gets the value of the billingInstructionCode property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBillingInstructionCode() {
        return billingInstructionCode;
    }

    /**
     * Sets the value of the billingInstructionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBillingInstructionCode(Double value) {
        this.billingInstructionCode = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the addTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAddTransaction() {
        return addTransaction;
    }

    /**
     * Sets the value of the addTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAddTransaction(Boolean value) {
        this.addTransaction = value;
    }

    /**
     * Gets the value of the addressID property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getAddressID() {
        return addressID;
    }

    /**
     * Sets the value of the addressID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setAddressID(UniqueID value) {
        this.addressID = value;
    }

    /**
     * Gets the value of the authorizerID property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getAuthorizerID() {
        return authorizerID;
    }

    /**
     * Sets the value of the authorizerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setAuthorizerID(UniqueID value) {
        this.authorizerID = value;
    }

    /**
     * Gets the value of the requestedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedBy() {
        return requestedBy;
    }

    /**
     * Sets the value of the requestedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedBy(String value) {
        this.requestedBy = value;
    }

    /**
     * Gets the value of the accountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * Sets the value of the accountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCode(String value) {
        this.accountCode = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCreditLimit(Double value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the limitUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLimitUsed() {
        return limitUsed;
    }

    /**
     * Sets the value of the limitUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLimitUsed(Double value) {
        this.limitUsed = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the declined property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeclined() {
        return declined;
    }

    /**
     * Sets the value of the declined property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeclined(Boolean value) {
        this.declined = value;
    }

    /**
     * Gets the value of the declinedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclinedBy() {
        return declinedBy;
    }

    /**
     * Sets the value of the declinedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclinedBy(String value) {
        this.declinedBy = value;
    }

    /**
     * Gets the value of the compVoucherNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompVoucherNo() {
        return compVoucherNo;
    }

    /**
     * Sets the value of the compVoucherNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompVoucherNo(String value) {
        this.compVoucherNo = value;
    }

    /**
     * Gets the value of the compCovers property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCompCovers() {
        return compCovers;
    }

    /**
     * Sets the value of the compCovers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCompCovers(Double value) {
        this.compCovers = value;
    }

    /**
     * Gets the value of the compTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompTypeCode() {
        return compTypeCode;
    }

    /**
     * Sets the value of the compTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompTypeCode(String value) {
        this.compTypeCode = value;
    }

    /**
     * Gets the value of the routingPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRoutingPercent() {
        return routingPercent;
    }

    /**
     * Sets the value of the routingPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRoutingPercent(Integer value) {
        this.routingPercent = value;
    }

    /**
     * Gets the value of the routingLimitType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingLimitType() {
        return routingLimitType;
    }

    /**
     * Sets the value of the routingLimitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingLimitType(String value) {
        this.routingLimitType = value;
    }

    /**
     * Gets the value of the membershipID property.
     * 
     * @return
     *     possible object is
     *     {@link UniqueID }
     *     
     */
    public UniqueID getMembershipID() {
        return membershipID;
    }

    /**
     * Sets the value of the membershipID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UniqueID }
     *     
     */
    public void setMembershipID(UniqueID value) {
        this.membershipID = value;
    }

    /**
     * Gets the value of the day1 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDay1() {
        return day1;
    }

    /**
     * Sets the value of the day1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDay1(Boolean value) {
        this.day1 = value;
    }

    /**
     * Gets the value of the day2 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDay2() {
        return day2;
    }

    /**
     * Sets the value of the day2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDay2(Boolean value) {
        this.day2 = value;
    }

    /**
     * Gets the value of the day3 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDay3() {
        return day3;
    }

    /**
     * Sets the value of the day3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDay3(Boolean value) {
        this.day3 = value;
    }

    /**
     * Gets the value of the day4 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDay4() {
        return day4;
    }

    /**
     * Sets the value of the day4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDay4(Boolean value) {
        this.day4 = value;
    }

    /**
     * Gets the value of the day5 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDay5() {
        return day5;
    }

    /**
     * Sets the value of the day5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDay5(Boolean value) {
        this.day5 = value;
    }

    /**
     * Gets the value of the day6 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDay6() {
        return day6;
    }

    /**
     * Sets the value of the day6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDay6(Boolean value) {
        this.day6 = value;
    }

    /**
     * Gets the value of the day7 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDay7() {
        return day7;
    }

    /**
     * Sets the value of the day7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDay7(Boolean value) {
        this.day7 = value;
    }

    /**
     * Gets the value of the dayString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayString() {
        return dayString;
    }

    /**
     * Sets the value of the dayString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayString(String value) {
        this.dayString = value;
    }

    /**
     * Gets the value of the daily property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDaily() {
        return daily;
    }

    /**
     * Sets the value of the daily property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDaily(Boolean value) {
        this.daily = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the room property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoom(String value) {
        this.room = value;
    }

    /**
     * Gets the value of the routingInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingInstruction() {
        return routingInstruction;
    }

    /**
     * Sets the value of the routingInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingInstruction(String value) {
        this.routingInstruction = value;
    }

    /**
     * Gets the value of the window property.
     * 
     */
    public int getWindow() {
        return window;
    }

    /**
     * Sets the value of the window property.
     * 
     */
    public void setWindow(int value) {
        this.window = value;
    }

}
