//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.21 at 06:33:28 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PointsInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointsInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AwardPointsInfo" type="{http://webservices.micros.com/og/4.3/Membership/}AwardPointsInfo" minOccurs="0"/>
 *         &lt;element name="TierPointsInfo" type="{http://webservices.micros.com/og/4.3/Membership/}TierPointsInfo" minOccurs="0"/>
 *         &lt;element name="StayPointsInfo" type="{http://webservices.micros.com/og/4.3/Membership/}StayPointsInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointsInfo", namespace = "http://webservices.micros.com/og/4.3/Membership/", propOrder = {
    "awardPointsInfo",
    "tierPointsInfo",
    "stayPointsInfo"
})
public class PointsInfo {

    @XmlElement(name = "AwardPointsInfo", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected AwardPointsInfo awardPointsInfo;
    @XmlElement(name = "TierPointsInfo", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected TierPointsInfo tierPointsInfo;
    @XmlElement(name = "StayPointsInfo", namespace = "http://webservices.micros.com/og/4.3/Membership/")
    protected StayPointsInfo stayPointsInfo;

    /**
     * Gets the value of the awardPointsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AwardPointsInfo }
     *     
     */
    public AwardPointsInfo getAwardPointsInfo() {
        return awardPointsInfo;
    }

    /**
     * Sets the value of the awardPointsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AwardPointsInfo }
     *     
     */
    public void setAwardPointsInfo(AwardPointsInfo value) {
        this.awardPointsInfo = value;
    }

    /**
     * Gets the value of the tierPointsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TierPointsInfo }
     *     
     */
    public TierPointsInfo getTierPointsInfo() {
        return tierPointsInfo;
    }

    /**
     * Sets the value of the tierPointsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TierPointsInfo }
     *     
     */
    public void setTierPointsInfo(TierPointsInfo value) {
        this.tierPointsInfo = value;
    }

    /**
     * Gets the value of the stayPointsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link StayPointsInfo }
     *     
     */
    public StayPointsInfo getStayPointsInfo() {
        return stayPointsInfo;
    }

    /**
     * Sets the value of the stayPointsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StayPointsInfo }
     *     
     */
    public void setStayPointsInfo(StayPointsInfo value) {
        this.stayPointsInfo = value;
    }

}
