//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 06:49:58 PM IST 
//


package com.micros.pms.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueueData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueueData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Guests" type="{http://webservices.micros.com/og/4.3/Name/}Customer" minOccurs="0"/>
 *         &lt;element name="RoomStay" type="{http://webservices.micros.com/og/4.3/HotelCommon/}RoomType" minOccurs="0"/>
 *         &lt;element name="FrontOfficeStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoomStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReservationRequest" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}ReservationRequestBase" minOccurs="0"/>
 *         &lt;element name="TimeInQueue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueueData", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/", propOrder = {
    "guests",
    "roomStay",
    "frontOfficeStatus",
    "roomStatus",
    "vipCode",
    "reservationRequest",
    "timeInQueue"
})
public class QueueData {

    @XmlElement(name = "Guests", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Customer guests;
    @XmlElement(name = "RoomStay", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected RoomType roomStay;
    @XmlElement(name = "FrontOfficeStatus", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String frontOfficeStatus;
    @XmlElement(name = "RoomStatus", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String roomStatus;
    @XmlElement(name = "VipCode", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String vipCode;
    @XmlElement(name = "ReservationRequest", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected ReservationRequestBase reservationRequest;
    @XmlElement(name = "TimeInQueue", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected String timeInQueue;

    /**
     * Gets the value of the guests property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getGuests() {
        return guests;
    }

    /**
     * Sets the value of the guests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setGuests(Customer value) {
        this.guests = value;
    }

    /**
     * Gets the value of the roomStay property.
     * 
     * @return
     *     possible object is
     *     {@link RoomType }
     *     
     */
    public RoomType getRoomStay() {
        return roomStay;
    }

    /**
     * Sets the value of the roomStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomType }
     *     
     */
    public void setRoomStay(RoomType value) {
        this.roomStay = value;
    }

    /**
     * Gets the value of the frontOfficeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontOfficeStatus() {
        return frontOfficeStatus;
    }

    /**
     * Sets the value of the frontOfficeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontOfficeStatus(String value) {
        this.frontOfficeStatus = value;
    }

    /**
     * Gets the value of the roomStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoomStatus() {
        return roomStatus;
    }

    /**
     * Sets the value of the roomStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoomStatus(String value) {
        this.roomStatus = value;
    }

    /**
     * Gets the value of the vipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVipCode() {
        return vipCode;
    }

    /**
     * Sets the value of the vipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVipCode(String value) {
        this.vipCode = value;
    }

    /**
     * Gets the value of the reservationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationRequestBase }
     *     
     */
    public ReservationRequestBase getReservationRequest() {
        return reservationRequest;
    }

    /**
     * Sets the value of the reservationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationRequestBase }
     *     
     */
    public void setReservationRequest(ReservationRequestBase value) {
        this.reservationRequest = value;
    }

    /**
     * Gets the value of the timeInQueue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeInQueue() {
        return timeInQueue;
    }

    /**
     * Sets the value of the timeInQueue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeInQueue(String value) {
        this.timeInQueue = value;
    }

}
