//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 06:49:58 PM IST 
//


package com.micros.ows.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Basic contact information for Hotel Property.
 * 
 * <p>Java class for ChainInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChainInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Addresses" type="{http://webservices.micros.com/og/4.3/HotelCommon/}AddressList" minOccurs="0"/>
 *         &lt;element name="ContactEmails" type="{http://webservices.micros.com/og/4.3/HotelCommon/}ContactEmailList" minOccurs="0"/>
 *         &lt;element name="ContactPhones" type="{http://webservices.micros.com/og/4.3/HotelCommon/}PhoneList" minOccurs="0"/>
 *         &lt;element name="MarketingText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoyaltyProgram" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BookingConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AcceptFrequenFlyerCard" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChainInfo", propOrder = {
    "addresses",
    "contactEmails",
    "contactPhones",
    "marketingText",
    "loyaltyProgram",
    "bookingConditions",
    "acceptFrequenFlyerCard"
})
public class ChainInfo {

    @XmlElement(name = "Addresses")
    protected AddressList addresses;
    @XmlElement(name = "ContactEmails")
    protected ContactEmailList contactEmails;
    @XmlElement(name = "ContactPhones")
    protected PhoneList contactPhones;
    @XmlElement(name = "MarketingText", required = true)
    protected String marketingText;
    @XmlElement(name = "LoyaltyProgram", required = true)
    protected String loyaltyProgram;
    @XmlElement(name = "BookingConditions", required = true)
    protected String bookingConditions;
    @XmlElement(name = "AcceptFrequenFlyerCard", required = true)
    protected String acceptFrequenFlyerCard;

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link AddressList }
     *     
     */
    public AddressList getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressList }
     *     
     */
    public void setAddresses(AddressList value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the contactEmails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactEmailList }
     *     
     */
    public ContactEmailList getContactEmails() {
        return contactEmails;
    }

    /**
     * Sets the value of the contactEmails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactEmailList }
     *     
     */
    public void setContactEmails(ContactEmailList value) {
        this.contactEmails = value;
    }

    /**
     * Gets the value of the contactPhones property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneList }
     *     
     */
    public PhoneList getContactPhones() {
        return contactPhones;
    }

    /**
     * Sets the value of the contactPhones property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneList }
     *     
     */
    public void setContactPhones(PhoneList value) {
        this.contactPhones = value;
    }

    /**
     * Gets the value of the marketingText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketingText() {
        return marketingText;
    }

    /**
     * Sets the value of the marketingText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketingText(String value) {
        this.marketingText = value;
    }

    /**
     * Gets the value of the loyaltyProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoyaltyProgram() {
        return loyaltyProgram;
    }

    /**
     * Sets the value of the loyaltyProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoyaltyProgram(String value) {
        this.loyaltyProgram = value;
    }

    /**
     * Gets the value of the bookingConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingConditions() {
        return bookingConditions;
    }

    /**
     * Sets the value of the bookingConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingConditions(String value) {
        this.bookingConditions = value;
    }

    /**
     * Gets the value of the acceptFrequenFlyerCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptFrequenFlyerCard() {
        return acceptFrequenFlyerCard;
    }

    /**
     * Sets the value of the acceptFrequenFlyerCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptFrequenFlyerCard(String value) {
        this.acceptFrequenFlyerCard = value;
    }

}
