//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 06:49:58 PM IST 
//


package com.micros.ows.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReservationRequest" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}ReservationRequestBase"/>
 *         &lt;element name="Printer" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}Printer" minOccurs="0"/>
 *         &lt;element name="CreditCardInfo" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}CreditCardInfo" minOccurs="0"/>
 *         &lt;element name="Transactions" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}Transaction" maxOccurs="8" minOccurs="0"/>
 *         &lt;element name="SignedDocument" type="{http://webservices.micros.com/og/4.3/Common/}FileData" minOccurs="0"/>
 *         &lt;element name="MembershipsList" type="{http://webservices.micros.com/og/4.3/ResvAdvanced/}MembershipsList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ApprovalCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DoNotMoveRoom" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="EmailFolio" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="EmailStaff" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="GetKeyTrack" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="KeyEncoder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="KeyExpirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Keys" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" />
 *       &lt;attribute name="KioskCall" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MobileKeyReferenceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MobilePhoneAudioKey" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="MobilePhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NoPost" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="PrintRegistration" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reservationRequest",
    "printer",
    "creditCardInfo",
    "transactions",
    "signedDocument",
    "membershipsList"
})
@XmlRootElement(name = "CheckInRequest", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
public class CheckInRequest {

    @XmlElement(name = "ReservationRequest", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/", required = true)
    protected ReservationRequestBase reservationRequest;
    @XmlElement(name = "Printer", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected Printer printer;
    @XmlElement(name = "CreditCardInfo", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected CreditCardInfo creditCardInfo;
    @XmlElement(name = "Transactions", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected List<Transaction> transactions;
    @XmlElement(name = "SignedDocument", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected FileData signedDocument;
    @XmlElement(name = "MembershipsList", namespace = "http://webservices.micros.com/og/4.3/ResvAdvanced/")
    protected MembershipsList membershipsList;
    @XmlAttribute(name = "ApprovalCode")
    protected String approvalCode;
    @XmlAttribute(name = "DoNotMoveRoom")
    protected Boolean doNotMoveRoom;
    @XmlAttribute(name = "EmailFolio")
    protected Boolean emailFolio;
    @XmlAttribute(name = "EmailStaff")
    protected Boolean emailStaff;
    @XmlAttribute(name = "GetKeyTrack")
    protected Boolean getKeyTrack;
    @XmlAttribute(name = "KeyEncoder")
    protected String keyEncoder;
    @XmlAttribute(name = "KeyExpirationDate")
    protected XMLGregorianCalendar keyExpirationDate;
    @XmlAttribute(name = "Keys")
    protected Integer keys;
    @XmlAttribute(name = "KioskCall")
    protected Boolean kioskCall;
    @XmlAttribute(name = "MobileKeyReferenceId")
    protected String mobileKeyReferenceId;
    @XmlAttribute(name = "MobilePhoneAudioKey")
    protected Boolean mobilePhoneAudioKey;
    @XmlAttribute(name = "MobilePhoneNumber")
    protected String mobilePhoneNumber;
    @XmlAttribute(name = "NoPost")
    protected Boolean noPost;
    @XmlAttribute(name = "PrintRegistration")
    protected Boolean printRegistration;

    /**
     * Gets the value of the reservationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ReservationRequestBase }
     *     
     */
    public ReservationRequestBase getReservationRequest() {
        return reservationRequest;
    }

    /**
     * Sets the value of the reservationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReservationRequestBase }
     *     
     */
    public void setReservationRequest(ReservationRequestBase value) {
        this.reservationRequest = value;
    }

    /**
     * Gets the value of the printer property.
     * 
     * @return
     *     possible object is
     *     {@link Printer }
     *     
     */
    public Printer getPrinter() {
        return printer;
    }

    /**
     * Sets the value of the printer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Printer }
     *     
     */
    public void setPrinter(Printer value) {
        this.printer = value;
    }

    /**
     * Gets the value of the creditCardInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreditCardInfo }
     *     
     */
    public CreditCardInfo getCreditCardInfo() {
        return creditCardInfo;
    }

    /**
     * Sets the value of the creditCardInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditCardInfo }
     *     
     */
    public void setCreditCardInfo(CreditCardInfo value) {
        this.creditCardInfo = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transactions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransactions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transaction }
     * 
     * 
     */
    public List<Transaction> getTransactions() {
        if (transactions == null) {
            transactions = new ArrayList<Transaction>();
        }
        return this.transactions;
    }

    /**
     * Gets the value of the signedDocument property.
     * 
     * @return
     *     possible object is
     *     {@link FileData }
     *     
     */
    public FileData getSignedDocument() {
        return signedDocument;
    }

    /**
     * Sets the value of the signedDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileData }
     *     
     */
    public void setSignedDocument(FileData value) {
        this.signedDocument = value;
    }

    /**
     * Gets the value of the membershipsList property.
     * 
     * @return
     *     possible object is
     *     {@link MembershipsList }
     *     
     */
    public MembershipsList getMembershipsList() {
        return membershipsList;
    }

    /**
     * Sets the value of the membershipsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MembershipsList }
     *     
     */
    public void setMembershipsList(MembershipsList value) {
        this.membershipsList = value;
    }

    /**
     * Gets the value of the approvalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalCode() {
        return approvalCode;
    }

    /**
     * Sets the value of the approvalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalCode(String value) {
        this.approvalCode = value;
    }

    /**
     * Gets the value of the doNotMoveRoom property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDoNotMoveRoom() {
        return doNotMoveRoom;
    }

    /**
     * Sets the value of the doNotMoveRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDoNotMoveRoom(Boolean value) {
        this.doNotMoveRoom = value;
    }

    /**
     * Gets the value of the emailFolio property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEmailFolio() {
        return emailFolio;
    }

    /**
     * Sets the value of the emailFolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmailFolio(Boolean value) {
        this.emailFolio = value;
    }

    /**
     * Gets the value of the emailStaff property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEmailStaff() {
        return emailStaff;
    }

    /**
     * Sets the value of the emailStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEmailStaff(Boolean value) {
        this.emailStaff = value;
    }

    /**
     * Gets the value of the getKeyTrack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGetKeyTrack() {
        return getKeyTrack;
    }

    /**
     * Sets the value of the getKeyTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGetKeyTrack(Boolean value) {
        this.getKeyTrack = value;
    }

    /**
     * Gets the value of the keyEncoder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyEncoder() {
        return keyEncoder;
    }

    /**
     * Sets the value of the keyEncoder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyEncoder(String value) {
        this.keyEncoder = value;
    }

    /**
     * Gets the value of the keyExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getKeyExpirationDate() {
        return keyExpirationDate;
    }

    /**
     * Sets the value of the keyExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setKeyExpirationDate(XMLGregorianCalendar value) {
        this.keyExpirationDate = value;
    }

    /**
     * Gets the value of the keys property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKeys() {
        return keys;
    }

    /**
     * Sets the value of the keys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKeys(Integer value) {
        this.keys = value;
    }

    /**
     * Gets the value of the kioskCall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isKioskCall() {
        return kioskCall;
    }

    /**
     * Sets the value of the kioskCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setKioskCall(Boolean value) {
        this.kioskCall = value;
    }

    /**
     * Gets the value of the mobileKeyReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileKeyReferenceId() {
        return mobileKeyReferenceId;
    }

    /**
     * Sets the value of the mobileKeyReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileKeyReferenceId(String value) {
        this.mobileKeyReferenceId = value;
    }

    /**
     * Gets the value of the mobilePhoneAudioKey property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMobilePhoneAudioKey() {
        return mobilePhoneAudioKey;
    }

    /**
     * Sets the value of the mobilePhoneAudioKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMobilePhoneAudioKey(Boolean value) {
        this.mobilePhoneAudioKey = value;
    }

    /**
     * Gets the value of the mobilePhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhoneNumber() {
        return mobilePhoneNumber;
    }

    /**
     * Sets the value of the mobilePhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhoneNumber(String value) {
        this.mobilePhoneNumber = value;
    }

    /**
     * Gets the value of the noPost property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoPost() {
        return noPost;
    }

    /**
     * Sets the value of the noPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoPost(Boolean value) {
        this.noPost = value;
    }

    /**
     * Gets the value of the printRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrintRegistration() {
        return printRegistration;
    }

    /**
     * Sets the value of the printRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrintRegistration(Boolean value) {
        this.printRegistration = value;
    }

}
