//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 06:49:58 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.micros.com/og/4.3/HotelCommon/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.micros.ows.bean;
