//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.05 at 06:49:58 PM IST 
//


package com.micros.ows.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Text" type="{http://webservices.micros.com/og/4.3/Common/}TextList" minOccurs="0"/>
 *         &lt;element name="IDs" type="{http://webservices.micros.com/og/4.3/Common/}IDPairList" minOccurs="0"/>
 *         &lt;element name="OperaErrorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="resultStatusFlag" type="{http://webservices.micros.com/og/4.3/Common/}ResultStatusFlag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultStatus", namespace = "http://webservices.micros.com/og/4.3/Common/", propOrder = {
    "text",
    "iDs",
    "operaErrorCode"
})
public class ResultStatus {

    @XmlElement(name = "Text", namespace = "http://webservices.micros.com/og/4.3/Common/")
    protected TextList text;
    @XmlElement(name = "IDs", namespace = "http://webservices.micros.com/og/4.3/Common/")
    protected IDPairList iDs;
    @XmlElement(name = "OperaErrorCode", namespace = "http://webservices.micros.com/og/4.3/Common/")
    protected String operaErrorCode;
    @XmlAttribute
    protected ResultStatusFlag resultStatusFlag;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link TextList }
     *     
     */
    public TextList getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextList }
     *     
     */
    public void setText(TextList value) {
        this.text = value;
    }

    /**
     * Gets the value of the iDs property.
     * 
     * @return
     *     possible object is
     *     {@link IDPairList }
     *     
     */
    public IDPairList getIDs() {
        return iDs;
    }

    /**
     * Sets the value of the iDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDPairList }
     *     
     */
    public void setIDs(IDPairList value) {
        this.iDs = value;
    }

    /**
     * Gets the value of the operaErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperaErrorCode() {
        return operaErrorCode;
    }

    /**
     * Sets the value of the operaErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperaErrorCode(String value) {
        this.operaErrorCode = value;
    }

    /**
     * Gets the value of the resultStatusFlag property.
     * 
     * @return
     *     possible object is
     *     {@link ResultStatusFlag }
     *     
     */
    public ResultStatusFlag getResultStatusFlag() {
        return resultStatusFlag;
    }

    /**
     * Sets the value of the resultStatusFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultStatusFlag }
     *     
     */
    public void setResultStatusFlag(ResultStatusFlag value) {
        this.resultStatusFlag = value;
    }

}
